### ISSUE TITLE
Stop Wiley journals demanding you read epdf

### ISSUE THREAD

**Issue by lmmx** [vsbuffalo/gmtfPDF#6]
In the same spirit as journals have used `pdf+html` link suffixes to make life difficult reading literature, Wiley have gone one stop further and is now removing all direct links to PDFs. Really annoying!

![](https://github.com/lmmx/devnotes/raw/master/Screenshot%20from%202015-03-15%2002:20:26.gif)
> — [`View full size`](https://github.com/lmmx/devnotes/raw/master/Screenshot%20from%202015-03-15%2002:20:26.gif)

> Finding all URLs on the page ending in "pdf" brings up both "epdf" and direct pdf links - but only the "epdf" ones are actually present on the page, and highlighted when you hover over them.

Reproduce the above in Chrome: `Ctrl`/`⌘` + `J`,

```javascript
links = document.querySelectorAll('a[href$="pdf"]')
```

Whereas PNAS is just an awkward use of frames on the webpage, Wiley rewrite the page in Javascript - since ReadCube is Javascript-based, this lets them use direct PDF links as a fallback.

This Chrome extension uses Javascript too and could switch the links back from `/epdf` to `/pdf`.

I guess you'd have to bump the version number in manifest.json, but should be a straightforward rule change, I'll send a PR.

**Comment by audy** [comment]
Came here to request this.

**Comment by vsbuffalo** [comment]
Sorry I've been swamped with stuff (prequalifying exam for my PhD) — I can pull in these and other changes early June.

**Comment by lmmx** [comment]
Cheers Vince, that'd be great. Hope studies have been going well!
